<a href="https://colab.research.google.com/github/quickgrid/CodeLab/blob/master/tensorflow/Tensorflow_Keras_Layer_Extraction_Name_Index_Mapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.applications import ResNet50, VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Conv2D
from keras.models import Model


model = ResNet50(weights='imagenet')
print(model.summary())


# Map layer to index vice versa
layer_name_to_index = {}
index_to_layer_name = {}
layers = []
for i, layer in enumerate(model.layers):
  layer_name_to_index['' + layer.name] = i
  index_to_layer_name[i] = layer.name
  layers.append(layer)



102973440/102967424 [==============================] - 1s 0us/step
Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 112, 112, 64) 256         conv1_conv[0][0]                 
________________________

In [7]:
print(layer_name_to_index['conv1_bn'])
print(index_to_layer_name[7])

3
conv2_block1_1_conv


In [12]:
tmp_layer = model.get_layer(index_to_layer_name[7])
print(tmp_layer.weights)

print("\n\nLength:")
print(len(tmp_layer.weights))

[<tf.Variable 'conv2_block1_1_conv/kernel:0' shape=(1, 1, 64, 64) dtype=float32, numpy=
array([[[[ 0.08688796, -0.26190212,  0.06590839, ..., -0.02883554,
          -0.16405106, -0.00745971],
         [ 0.01356522,  0.02057924, -0.03024781, ..., -0.01544086,
           0.02114245, -0.02121195],
         [-0.02776849, -0.00934073,  0.00506952, ..., -0.00039864,
          -0.00157149,  0.00997116],
         ...,
         [-0.00766947,  0.00688486,  0.00997647, ..., -0.0170019 ,
           0.00468291,  0.03455077],
         [-0.02132323,  0.01440203, -0.00365784, ...,  0.01140573,
          -0.01464687,  0.0494004 ],
         [-0.01673706,  0.01452293, -0.26559788, ...,  0.02150083,
          -0.10702326, -0.08648951]]]], dtype=float32)>, <tf.Variable 'conv2_block1_1_conv/bias:0' shape=(64,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0

In [16]:
print(tmp_layer.trainable_weights)
print('\n\n')
print(tmp_layer.non_trainable_weights)

[<tf.Variable 'conv2_block1_1_conv/kernel:0' shape=(1, 1, 64, 64) dtype=float32, numpy=
array([[[[ 0.08688796, -0.26190212,  0.06590839, ..., -0.02883554,
          -0.16405106, -0.00745971],
         [ 0.01356522,  0.02057924, -0.03024781, ..., -0.01544086,
           0.02114245, -0.02121195],
         [-0.02776849, -0.00934073,  0.00506952, ..., -0.00039864,
          -0.00157149,  0.00997116],
         ...,
         [-0.00766947,  0.00688486,  0.00997647, ..., -0.0170019 ,
           0.00468291,  0.03455077],
         [-0.02132323,  0.01440203, -0.00365784, ...,  0.01140573,
          -0.01464687,  0.0494004 ],
         [-0.01673706,  0.01452293, -0.26559788, ...,  0.02150083,
          -0.10702326, -0.08648951]]]], dtype=float32)>, <tf.Variable 'conv2_block1_1_conv/bias:0' shape=(64,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0

In [17]:
tmp_layer.trainable = False

In [18]:
print(tmp_layer.trainable_weights)
print('\n\n')
print(tmp_layer.non_trainable_weights)

[]



[<tf.Variable 'conv2_block1_1_conv/kernel:0' shape=(1, 1, 64, 64) dtype=float32, numpy=
array([[[[ 0.08688796, -0.26190212,  0.06590839, ..., -0.02883554,
          -0.16405106, -0.00745971],
         [ 0.01356522,  0.02057924, -0.03024781, ..., -0.01544086,
           0.02114245, -0.02121195],
         [-0.02776849, -0.00934073,  0.00506952, ..., -0.00039864,
          -0.00157149,  0.00997116],
         ...,
         [-0.00766947,  0.00688486,  0.00997647, ..., -0.0170019 ,
           0.00468291,  0.03455077],
         [-0.02132323,  0.01440203, -0.00365784, ...,  0.01140573,
          -0.01464687,  0.0494004 ],
         [-0.01673706,  0.01452293, -0.26559788, ...,  0.02150083,
          -0.10702326, -0.08648951]]]], dtype=float32)>, <tf.Variable 'conv2_block1_1_conv/bias:0' shape=(64,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.,

### Layer insertion in middle
https://stackoverflow.com/questions/45306433/removing-then-inserting-a-new-middle-layer-in-a-keras-model

In [19]:
print(layer_name_to_index['conv2_block2_1_conv'])

19


In [29]:
vgg_model = VGG16(weights='imagenet')
print(vgg_model.summary())

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [30]:
# Disassemble layers
net_layers = [l for l in vgg_model.layers]

# Defining new convolutional layer.
# Important: the number of filters should be the same!
# Note: the receiptive field of two 3x3 convolutions is 5x5.
new_conv = Conv2D(filters=64, 
                  kernel_size=(5, 5),
                  name='new_conv',
                  padding='same')(net_layers[0].output)

# Now stack everything back
# Note: If you are going to fine tune the model, do not forget to
#       mark other layers as un-trainable

x = new_conv
for i in range(3, len(net_layers)):
    net_layers[i].trainable = False
    x = net_layers[i](x)

# Final touch
result_model = Model(inputs=net_layers[0].input, outputs=x)
result_model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
new_conv (Conv2D)            (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
_________________________________________________________________
block3_conv1 (Conv2D)        (None, 56, 56, 256)       2951

In [32]:
!wget "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/RayBanAviator.jpg/1200px-RayBanAviator.jpg" -O "sunglass.jpg"

--2021-03-12 15:30:25--  https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/RayBanAviator.jpg/1200px-RayBanAviator.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 208.80.154.240, 2620:0:861:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|208.80.154.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 59553 (58K) [image/jpeg]
Saving to: ‘sunglass.jpg’

sunglass.jpg        100%[===================>]  58.16K  --.-KB/s    in 0.003s  

2021-03-12 15:30:25 (21.2 MB/s) - ‘sunglass.jpg’ saved [59553/59553]



In [33]:
img_path = 'sunglass.jpg'

img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
 
#decode the results into a list of tuples (class, description, probability)
#(one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])

40960/35363 [==================================] - 0s 0us/step
Predicted: [('n04355933', 'sunglass', 0.8776379), ('n04356056', 'sunglasses', 0.12236167), ('n03692522', 'loupe', 1.2771386e-07)]


In [34]:
# Bad results since the layer weights are just random and not trained
preds = result_model.predict(x)
 
#decode the results into a list of tuples (class, description, probability)
#(one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])

Predicted: [('n04286575', 'spotlight', 0.029787757), ('n02786058', 'Band_Aid', 0.02791295), ('n03584254', 'iPod', 0.027093599)]


In [35]:
preds = vgg_model.predict(x)
 
#decode the results into a list of tuples (class, description, probability)
#(one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])

Predicted: [('n04355933', 'sunglass', 0.83338046), ('n04356056', 'sunglasses', 0.15567955), ('n03759954', 'microphone', 0.003415848)]
